name: Update Files
on:
  repository_dispatch:
    types: [file-update]
  workflow_dispatch:
jobs:
  file-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          ref: master
      - run: |
          wget https://raw.githubusercontent.com/NebraLtd/helium-miner-software/master/balena/balena.yml.og -O /home/runner/work/helium-og/helium-og/balena.yml
          wget https://raw.githubusercontent.com/NebraLtd/helium-miner-software/master/device-compose-files/docker-compose-rpi.yml -O /home/runner/work/helium-og/helium-og/docker-compose.yml
      - name: Push updated docker compose file (Pisces)
        if: success()
        uses: test-room-7/action-update-file@v1
        with:
          branch: master
          file-path: /home/runner/work/helium-og/helium-og/*.yml
          commit-msg: Update balena.yml and docker-compose.yml              
          github-token: ${{ secrets.MR_BUMP }}
